---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-sts-silicom-tox-py39
        - k8sapp-sts-silicom-tox-pylint
        - k8sapp-sts-silicom-tox-flake8
        - k8sapp-sts-silicom-tox-metadata
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-sts-silicom-tox-py39
        - k8sapp-sts-silicom-tox-pylint
        - k8sapp-sts-silicom-tox-flake8
        - k8sapp-sts-silicom-tox-metadata
    post:
      jobs:
        - stx-app-sts-silicom-upload-git-mirror

- job:
    name: k8sapp-sts-silicom-tox-py39
    parent: openstack-tox-py39
    description: |
        Run py39 for sts-silicom app
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-sts-silicom/*
    vars:
        tox_extra_args: -c python3-k8sapp-sts-silicom/k8sapp_sts_silicom/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-sts-silicom-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp_sts_silicom
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-sts-silicom/k8sapp_sts_silicom/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-sts-silicom-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp_sts_silicom
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-sts-silicom/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-sts-silicom/k8sapp_sts_silicom/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-sts-silicom-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp_sts_silicom
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-sts-silicom/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-sts-silicom/k8sapp_sts_silicom/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-app-sts-silicom-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/app-sts-silicom to
      github.com/starlingx/app-sts-silicom
    vars:
      git_mirror_repository: starlingx/app-sts-silicom
    secrets:
      - name: git_mirror_credentials
        secret: stx-app-sts-silicom-github-secret3
        pass-to-parent: true


- secret:
    name: stx-app-sts-silicom-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - JZb5T9s1t6JQUWA5Y35OMsnfF0RLKH9tfG9v0OVs+6PoB4BUUlgyuzUXOM2ZHMcnOBuUa
          b1Jm1qjLdcVvl2SgdtvX8MEsYgSbmAFcul3veQF3FjJo5qZoG1hcFZSIwuCHHgUMZCGT1
          nec5xi+bzEQWButnb+SiewDpr6CcO9upWpG4BwzgqLARCMky7Zbpzylg3bA9r/cEW6chB
          CQyNpBQSsPMnxcz4Rz+vp+BFzaGp+XAUM9Z7onbZvpDCbWCEyhbggS9kgan9xPJzaWxaY
          Ms9zMU41zAZ/5d23pIBmWPeZKS4EJ0N6rEjXTbvW9BOA9GhKDB99YStSShPREz80kCfBL
          NYFKIJli62PZIBmwrJDeC26offGmsb7xmXAPyeWUxTSqZY/62/81/dTX2EHNZYdnEVcXw
          y+lkmxGZ42DDX7PlBSGWv7O+M9xsUKaK5Q+1SWDXyzjkwYXXJg4RG0VMT20Z16EKBhTxo
          y2snb5GNfb1KRVU2lOjHlC/TGBZ6OJLu8DYuVJXoU3EdmWiORE+HSsqkydmca61W1IhQr
          uFWnXKzEkwMs185i9PbTMT8tq8UBs2d57UKpHI2X4Qsf9wJG2hG7gsNYdqHnPBpJ/k3WJ
          ddceuJ2mbf/Vngle4bLL9EzCNxbYtDdadK/RoawUku2117XHBqHPQH0ARQKQU8=
        - Zbm4F7aNV9NbHJZdYAheonSzfXre0Irxsy+5UWfCyAuWq68ZiZfSsCk9FqF5oXes7M+RF
          8Yn7zYYPJ4/HG9HvI9CxJXn7QJWEf23xFFMP6Zpx9x6o39cU5QXmZ+riUgXuFIeXUVhml
          +rTtG/92O1Qm5Tdplsz71iK9u7vDqgkQlAopXCdqJH3GIQpYfEhxkKzS0prC4AFiN+TGg
          vub1yFwBCYLZn9DCnt1NnYdG1b1XYQ629l3DJGQti/DJop9cmox6aXkMeTbyEUnnx8Gaf
          2jd3Ge2i6HWRmlA2L1zN/kOKyv3ensK3Pdd1aSv4cIDg0GsJ7eWX/PW1yx1tpaMT83lpU
          4NBPlyl39NTvX/a6tu8oGPsYLUgLoPj6gNwQov7jJYJxzxVntD6f4/OrR1MahBG4ukHI9
          +VVYrXelXKP3OkCBYYZOa7KesXfJeFd2Zt0gaU6qXLvcIywbJuUtf9BCkLBUbx4z/mHoV
          CZQucLUW+NNPT+cKuDWgjxMueVw37/U7Xc7GWWm2zEpbcIGu1OAnXixZqGGUe1KPVqobp
          xYb0xzJtvl9vK9xwf3PwqxdZazb72QvQbhblbeEmAL5LU1gBB0jV6LyyCfBd+1XnLV6po
          41vW4ns+kSIojuKs9O+AnKXLVEHCOuy4aL64fQD6RxvrUCIvQOQLy/lZ0ESD94=
        - GKG0bGl7uW+rqINWf5iSBPa9/0t0BMzc0KFXIZYMXNHtkFBTruWNCL1YSu/n7ignFlhwP
          jVYUcRBHTfkMNJOauhueozfzows58LpATKXLDNfhVOIjgcwrTnT4OSVD9BBT9iXP2jfuU
          SPE7keF9On9p6JD+rCDpfJE20S4VjfhkdpZsYJS8/hgcenKFXr5CEzaIchwW3+Vn31jx3
          71xWt45/Vlpai8BIgNV4eBZvZpAQ4WJXIUBTa8ooeVGXVbfyliJ0bJjvCPNbN7nyj7Mht
          ztDkTyz8KeYJeeZDzX8oq4ovulDWGXS96DWcYtWOiTwqdaejiJRob//l1cFXMfI1AH91S
          7urpexWXVP0IOvBfLlhQw0pnLEsS52IdhEZS575+NZQeOlMSD+KIafE+ULX/JfWcdySiP
          wNjC4ZTadur5kJzQSb/JLDVnwh+XDyS9oL6YlXb3JyZvyG7DlJhlQ9lHnndEE63NiKKWg
          gAHiI4v9D756tyMGRbGQpbRaC0XZBT5ulYSqHicX7XreF9wG25s5+cJbEaPI00Sin+pT3
          MmQArI7CdPZd02LuzMCzm+C238Etjwu0INgtRvCxAtQAiu5hDXsZFZlxNjDlBQXTc6Waq
          9odkZxvNZZEA0PvW5hDZdgJKnlZSlRbp+6/lNKwtU9IP4W0RsvVR8gWoCs2QPU=
        - coPzCH3vtG4ZA+bv/YOhhD0t0cNmSd59mkSWcudshdV6WuwVvtfpUJtNNiGOkCKlyuQkW
          XZ7kg0SjS4kyURVfVa+OYAeFfekSstEnI74wx0jVzPydaomog4kDoCgRlEJXAUU1Hoaz5
          3vk8X907Bah1cpaqZB+wmg/LnDYqVbszDbD4wDG9LHA8+NH/BQNFeRAjkj0YDpFE+O1ja
          /ImFgzonoxP3O43jcKwGGGan7r3BYJBupitUsJUnSGq9lI6BwPtjm3zRIpDBkyIzv4it+
          dz30eb7PtYPn946qjaLQmLlxBdd09TDRyeyw8vxkw+T06aRmbBdXDOaAOvYwAss6iY9p0
          iKQwbcbpL3NixC52r+8fYeP/bxYr6n98ZbXStGES07bKfueu1SCEudAkCxKjYwLCgoRjX
          GE+zIZW/Ny6FtweX56Ioey9S5MZechd13Fac2CnN5HQTNdT4CZ9mJ6+2ExrEnGBiDj5gV
          Ua3YZNFUu+4E8Kfd000kluKb0eYqAxMUUdA6e/HsnT4KYtGA4WLEJSeFh//p7OMKN/Auc
          mvZXcc0BHjmQwxxaLTZ3NMg/mLTRuxo5MqJQhqm+DijTiDv/BStXkBeX5Jb6r81HiLGNs
          1zFFaM/fSfYdecTN+WnHNUFojOpHM27uB0Jn9HBhLb7P4Qd0LXdxFV5I8GUfeY=
        - myncApoIbaQAxCWvzx1KD56/1UMrNm9Nwe20oQhYkA6IlQ2kLiGuD782r17YAdoBZuJak
          bhBwmawJK/nc37Rt4oatk2jKoLlW6nYFwmUhIUyqpfF1W8qd4NlRXm3D3lbN50ZSBSKtY
          BKH5mvySGa520LL/zhmval+6ZddORHBoL/D6xNMOjSaU3pXAo0BXJaK5nHwA9/vn1jHmu
          bKGJ1++NsarOMC/zk2UpTR7cVFNpgD/c+GHhehHY0V9td/VRl64TsLLUW4BXgMbZ5KmKR
          IH8bWVeejBohZg01I/MIYTYJzho/srn+qbCKGBVxDpHZus1WjC8Ng0cDFC2K/CjyJh3hg
          JwgAF6sDZJccUOXRGX1llfSAwdwSjKoIgFnW3BOUMQhRKFmBkMOQkrD09sDPdIGTCQlQ+
          BZO285AfM1r0+lmBl1BAQH74D2XMh7vhLx7bTdwDIjDuz3Ig4k0I55HKNm0m+1DDl+dXO
          Tm5B7GeMRnZ4TGyf9/+DvtE1LCFRT4mS3B5O3dbUNmFk0UbUadJ3W0BKqu+8UUTxVF9JE
          UKJtUGKqeIf1ui2iGeSrKHDC7UWLqqLFqke/c8MkGyh2Q6UkTFjyNJRDPDPr/3TpdTlpK
          chZ8ASijO8j8e8v+vHE6mNm9PMv+j1ZnipP5pRErhKv+Qv7T9ZTG2lGc8V/ITw=
        - B79mkednlw+MpzNXejB/oohgoMnOOkx9svAGYrBLFzC6LdL3ThT866vSDJLkhgSMvfNQD
          sGnRsjLkrigI5zgn/7gJ76f4Qum92tjOfnDcVy6EWlXiTGehaUVJjBlGtJcGFzGzTwJ+N
          U/Z5kX0tQuCQM1WlLK2Gf0KR7kQANypcZQzYxuKo4dJDZrzOGeZretvPEFM8GTdq6ekb/
          7Ztv8qvm07OrioCEY8q1OeyVUp/qhfFgjSYWj/fAq98NqQDxjQhHlQICpVAwcA/McdgP/
          8p6G6IJ/+iI5HJshslTk42LiaohfhEg9+8Ioky8cjXpuTV7p/z6RFp3kInRTv1Onolgfn
          f08eErXWqaGrFjmEI9kea/aOjWzulfBgr5CeMLe95m20rpfsxB2fqIVh4t3NIQJ4g4ElM
          2Ur0N7741gFfZStpC5qVwVyIPInJKcrKtaw5CbEMp7uP8viWan6OlUrNbFUigLoyTpXrd
          wjv9VyOKYrHUScciDXVHfLcjJGgz2cOlC5jKZMvrihH4F5s4Al3mv8boxKj5hAGRwZ7F6
          Kuo9k0iS0or1kL8knC6KMm7h/OOO/qphO+sZHx0T3cXM5DH9k1DerfK9JR4uYVI2QL44C
          DUDkxq/9DKuuSgEVr4jyWqzPff9UELzPS1Czqf37LxVlQPKidA5z+nPkar9HxE=
        - usRuJylHBQk96L9MedBex9d2Kd+ifGQ/SOwMb9woP6Z9oDBVVxloYGc3vQnPTBG1z55c4
          f9487odxFdsMZeyIDq7fWstP9Vfj3YsMlQTVO8TbGLqoL+RTWO92TU3WJ+X/Jh+gJGOH8
          E2AlLkXb+Zi1upCcH3vmEIkeFLg6DSX7T/RC9eXB+TmtcEptL9MOSNaXFz4SshMRapsrd
          GtKor1cx/6GZ4LMet2/5VJ2Ef/lktybsIKyY9TxIoK9v+1T0j3YpfuK9MKnlnLgnXOpGR
          TsR/qiOhFrsiQNZ2/2evrAUXHifaCg9f56g8uz1u1g85lQOx3s3K7s5WZ+vBaU5HOhI3t
          kwH0IB330/R1T1xYIHqb0pF0stGZU7sq2UK+EGyW0k073f/aSrjKuROa9HkFcLLT8JKQk
          eFIm0yM84My14S12tya/8dhn1DvAzdGyvIsInq3igt9rDMYkVcxUckTj5UcWuubo9HL4/
          sKs6AS0Uk+PfC2l6GIZ8FZ1ThUV7Xk1dTGH3pw6fDva1s9E8hJc4iLX4h/HrnQ7+yk6iF
          L5/F2QvguXW//k/kHOAyrpcRJ0HnDzovkXV25sNw20ce1Kpv5KFcWFZKTYLgTUWvARUEu
          f0ldXo8L11eFmKAGoQQ5329TjOcznQKZT8uQqTmPsROhQMNPYt+1+fmDiSObjo=
