#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: sts-silicom
  labels:
    chart_group: sts-silicom-charts
spec:
  releaseName: sts-silicom
  chart:
    spec:
      chart: sts-silicom
      version: REPLACE_HELM_CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: sts-silicom-static-overrides
      valuesKey: sts-silicom-static-overrides.yaml
    - kind: Secret
      name: sts-silicom-system-overrides
      valuesKey: sts-silicom-system-overrides.yaml
