#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

namespace: sts-silicom
resources:
  - helmrelease.yaml
secretGenerator:
  - name: sts-silicom-static-overrides
    files:
      - sts-silicom-static-overrides.yaml
  - name: sts-silicom-system-overrides
    files:
      - sts-silicom-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
